# ML lec 04 - multi-variable linear regression

---

#### Multi-variable

![대체 텍스트](https://i.imgur.com/VD8U5OL.png)

값이 많을 경우 위와 같이 복잡해지게되고 그로인해 사용하는 것이 행렬!

#### Matrix multiplication

![대체 텍스트](https://i.imgur.com/bASuQGV.png)

#### Hypothesis using matrix

![대체 텍스트](https://i.imgur.com/VD8U5OL.png)

![대체 텍스트](https://i.imgur.com/oFMsSPc.png)

![대체 텍스트](https://i.imgur.com/AJPyUqv.png)

![대체 텍스트](https://i.imgur.com/iZWX3Fv.png)

           [5,3]                   [3,1]                             [5,1]
           
[n,3] [3,1] = [n,1]

전보다 복잡하지 않고 간결하게 표시 및 계산 가능

# ML lab 04-1: multi-variable linear regression을 TensorFlow에서 구현하기 (new)

In [2]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  11366.695 
Prediction:
 [63.39946  66.89693  71.169106 72.95558  52.272675]
10 Cost:  15.170351 
Prediction:
 [157.63551 180.18845 182.78319 194.50284 138.6903 ]
20 Cost:  14.996496 
Prediction:
 [157.90648 180.54083 183.11646 194.86804 138.96385]
30 Cost:  14.926847 
Prediction:
 [157.89317 180.55153 183.11308 194.86668 138.97673]
40 Cost:  14.857547 
Prediction:
 [157.87906 180.56117 183.10864 194.8642  138.98877]
50 Cost:  14.788733 
Prediction:
 [157.86497 180.57076 183.10426 194.8617  139.00078]
60 Cost:  14.720218 
Prediction:
 [157.85092 180.58032 183.09985 194.85919 139.01274]
70 Cost:  14.652056 
Prediction:
 [157.83691 180.58986 183.09543 194.8567  139.02467]
80 Cost:  14.584242 
Prediction:
 [157.8229  180.59937 183.09106 194.85422 139.03658]
90 Cost:  14.516828 
Prediction:
 [157.80898 180.60887 183.08672 194.85176 139.04845]
100 Cost:  14.449771 
Prediction:
 [157.79506 180.61832 183.08237 194.8493  139.06029]
110 Cost:  14.383028 
Prediction:
 [157.7812  180.6277

1590 Cost:  7.5701437 
Prediction:
 [156.0851  181.78038 182.54536 194.56166 140.50032]
1600 Cost:  7.539945 
Prediction:
 [156.07578 181.78674 182.54243 194.56018 140.50812]
1610 Cost:  7.509862 
Prediction:
 [156.06642 181.79305 182.53947 194.5587  140.51585]
1620 Cost:  7.4799027 
Prediction:
 [156.0571  181.79936 182.53653 194.55724 140.52357]
1630 Cost:  7.4501314 
Prediction:
 [156.04782 181.80566 182.5336  194.55579 140.53128]
1640 Cost:  7.420555 
Prediction:
 [156.03859 181.81197 182.53069 194.55434 140.53894]
1650 Cost:  7.3910584 
Prediction:
 [156.02934 181.81824 182.52779 194.5529  140.54663]
1660 Cost:  7.3617735 
Prediction:
 [156.02013 181.82445 182.52484 194.55145 140.55424]
1670 Cost:  7.3326635 
Prediction:
 [156.01097 181.8307  182.52199 194.55002 140.5619 ]
1680 Cost:  7.303605 
Prediction:
 [156.00177 181.83691 182.51907 194.5486  140.56946]
1690 Cost:  7.2748046 
Prediction:
 [155.99265 181.8431  182.51619 194.54716 140.57704]
1700 Cost:  7.246115 
Prediction:
 [

In [3]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  1908.5084 
Prediction:
 [[120.86813]
 [133.05563]
 [137.48494]
 [148.11443]
 [ 99.87431]]
10 Cost:  28.998077 
Prediction:
 [[159.19682]
 [179.16339]
 [182.89514]
 [197.56737]
 [135.05078]]
20 Cost:  28.8251 
Prediction:
 [[159.29196]
 [179.31715]
 [183.02617]
 [197.71239]
 [135.17592]]
30 Cost:  28.670094 
Prediction:
 [[159.27148]
 [179.33186]
 [183.02019]
 [197.70825]
 [135.19496]]
40 Cost:  28.51591 
Prediction:
 [[159.25072]
 [179.34612]
 [183.01384]
 [197.70367]
 [135.21365]]
50 Cost:  28.362743 
Prediction:
 [[159.23003]
 [179.3603 ]
 [183.00748]
 [197.69911]
 [135.23225]]
60 Cost:  28.210333 
Prediction:
 [[159.20937]
 [179.37445]
 [183.00114]
 [197.69453]
 [135.25081]]
70 Cost:  28.058636 
Prediction:
 [[159.18874]
 [179.38858]
 [182.99484]
 [197.68999]
 [135.26932]]
80 Cost:  27.907864 
Prediction:
 [[159.1682 ]
 [179.40265]
 [182.98853]
 [197.68546]
 [135.28778]]
90 Cost:  27.757824 
Prediction:
 [[159.14772]
 [179.41672]
 [182.98225]
 [197.68094]
 [135.30621]]
100 

1620 Cost:  12.20137 
Prediction:
 [[156.58441]
 [181.17365]
 [182.19638]
 [197.11577]
 [137.6091 ]]
1630 Cost:  12.136277 
Prediction:
 [[156.57089]
 [181.18288]
 [182.19223]
 [197.11278]
 [137.62122]]
1640 Cost:  12.071552 
Prediction:
 [[156.55743]
 [181.19211]
 [182.1881 ]
 [197.10982]
 [137.6333 ]]
1650 Cost:  12.007093 
Prediction:
 [[156.54399]
 [181.20132]
 [182.18398]
 [197.10686]
 [137.64537]]
1660 Cost:  11.943083 
Prediction:
 [[156.53061]
 [181.2105 ]
 [182.17987]
 [197.1039 ]
 [137.6574 ]]
1670 Cost:  11.879347 
Prediction:
 [[156.51726]
 [181.21967]
 [182.1758 ]
 [197.10098]
 [137.66942]]
1680 Cost:  11.815971 
Prediction:
 [[156.50394]
 [181.2288 ]
 [182.1717 ]
 [197.09805]
 [137.68138]]
1690 Cost:  11.752962 
Prediction:
 [[156.49065]
 [181.2379 ]
 [182.16762]
 [197.09511]
 [137.6933 ]]
1700 Cost:  11.690274 
Prediction:
 [[156.47739]
 [181.24698]
 [182.16354]
 [197.09218]
 [137.70518]]
1710 Cost:  11.627975 
Prediction:
 [[156.46419]
 [181.25603]
 [182.1595 ]
 [197.08

https://wikidocs.net/14#_4

python slice 참고링크

In [9]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('https://raw.githubusercontent.com/Crpediem/DeepLearningZeroToAll/master/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost:  132275.3 
Prediction:
 [[-185.4328 ]
 [-227.07315]
 [-221.36308]
 [-242.03189]
 [-173.73509]
 [-130.63005]
 [-181.85593]
 [-135.5162 ]
 [-214.65685]
 [-201.69966]
 [-175.49187]
 [-175.44582]
 [-227.63377]
 [-188.23065]
 [-183.47328]
 [-231.01451]
 [-179.41754]
 [-217.6085 ]
 [-216.22025]
 [-193.32082]
 [-213.27763]
 [-

690 Cost:  17.546154 
Prediction:
 [[155.4465  ]
 [184.22063 ]
 [183.02306 ]
 [198.98227 ]
 [139.83736 ]
 [101.676254]
 [148.71562 ]
 [110.14138 ]
 [170.83652 ]
 [156.8447  ]
 [142.84682 ]
 [139.37643 ]
 [189.55937 ]
 [157.81764 ]
 [148.92218 ]
 [186.78374 ]
 [149.9038  ]
 [179.12495 ]
 [181.1726  ]
 [162.18936 ]
 [174.38196 ]
 [172.46843 ]
 [166.57306 ]
 [157.7459  ]
 [191.64626 ]]
700 Cost:  17.445766 
Prediction:
 [[155.43364 ]
 [184.22452 ]
 [183.01631 ]
 [198.98247 ]
 [139.83891 ]
 [101.69131 ]
 [148.72156 ]
 [110.153305]
 [170.85387 ]
 [156.87918 ]
 [142.85056 ]
 [139.39156 ]
 [189.545   ]
 [157.79622 ]
 [148.93187 ]
 [186.7931  ]
 [149.88022 ]
 [179.13237 ]
 [181.15474 ]
 [162.17264 ]
 [174.38902 ]
 [172.47821 ]
 [166.57599 ]
 [157.71567 ]
 [191.64372 ]]
710 Cost:  17.34627 
Prediction:
 [[155.42087]
 [184.22841]
 [183.00961]
 [198.98267]
 [139.84045]
 [101.70628]
 [148.72748]
 [110.1652 ]
 [170.87115]
 [156.91351]
 [142.8543 ]
 [139.4066 ]
 [189.53072]
 [157.77489]
 [148.94153]

1470 Cost:  11.846423 
Prediction:
 [[154.6053 ]
 [184.468  ]
 [182.5772 ]
 [198.99803]
 [139.92506]
 [102.66147]
 [149.11986]
 [110.95251]
 [171.97215]
 [159.11726]
 [143.0965 ]
 [140.37013]
 [188.60738]
 [156.3937 ]
 [149.57173]
 [187.39641]
 [148.32936]
 [179.63521]
 [179.9915 ]
 [161.08734]
 [174.85829]
 [173.1094 ]
 [166.77757]
 [155.74934]
 [191.46883]]
1480 Cost:  11.795647 
Prediction:
 [[154.5964 ]
 [184.4705 ]
 [182.57243]
 [198.99823]
 [139.9258 ]
 [102.6719 ]
 [149.12433]
 [110.96149]
 [171.98418]
 [159.14154]
 [143.0992 ]
 [140.3807 ]
 [188.59712]
 [156.37836]
 [149.57881]
 [187.40288]
 [148.31227]
 [179.64093]
 [179.97884]
 [161.07558]
 [174.86351]
 [173.1162 ]
 [166.77989]
 [155.72798]
 [191.46683]]
1490 Cost:  11.745322 
Prediction:
 [[154.58755]
 [184.47304]
 [182.5677 ]
 [198.99844]
 [139.92654]
 [102.68228]
 [149.1288 ]
 [110.97044]
 [171.99615]
 [159.1657 ]
 [143.1019 ]
 [140.39124]
 [188.58696]
 [156.36308]
 [149.58586]
 [187.40935]
 [148.29526]
 [179.64665]
 [179.